onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /TestCordic/clk
add wave -noupdate /TestCordic/rst
add wave -noupdate -radix decimal -childformat {{{/TestCordic/ang[9]} -radix decimal} {{/TestCordic/ang[8]} -radix decimal} {{/TestCordic/ang[7]} -radix decimal} {{/TestCordic/ang[6]} -radix decimal} {{/TestCordic/ang[5]} -radix decimal} {{/TestCordic/ang[4]} -radix decimal} {{/TestCordic/ang[3]} -radix decimal} {{/TestCordic/ang[2]} -radix decimal} {{/TestCordic/ang[1]} -radix decimal} {{/TestCordic/ang[0]} -radix decimal}} -radixshowbase 0 -subitemconfig {{/TestCordic/ang[9]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[8]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[7]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[6]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[5]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[4]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[3]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[2]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[1]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/ang[0]} {-height 15 -radix decimal -radixshowbase 0}} /TestCordic/ang
add wave -noupdate -radix decimal -radixshowbase 0 /TestCordic/theCordic/lam
add wave -noupdate -format Analog-Step -height 74 -max 510.99999999999989 -min -509.0 -radix decimal -childformat {{{/TestCordic/cos[9]} -radix decimal} {{/TestCordic/cos[8]} -radix decimal} {{/TestCordic/cos[7]} -radix decimal} {{/TestCordic/cos[6]} -radix decimal} {{/TestCordic/cos[5]} -radix decimal} {{/TestCordic/cos[4]} -radix decimal} {{/TestCordic/cos[3]} -radix decimal} {{/TestCordic/cos[2]} -radix decimal} {{/TestCordic/cos[1]} -radix decimal} {{/TestCordic/cos[0]} -radix decimal}} -radixshowbase 0 -subitemconfig {{/TestCordic/cos[9]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[8]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[7]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[6]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[5]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[4]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[3]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[2]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[1]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/cos[0]} {-height 15 -radix decimal -radixshowbase 0}} /TestCordic/cos
add wave -noupdate -format Analog-Step -height 74 -max 510.99999999999989 -min -507.0 -radix decimal -childformat {{{/TestCordic/sin[9]} -radix decimal} {{/TestCordic/sin[8]} -radix decimal} {{/TestCordic/sin[7]} -radix decimal} {{/TestCordic/sin[6]} -radix decimal} {{/TestCordic/sin[5]} -radix decimal} {{/TestCordic/sin[4]} -radix decimal} {{/TestCordic/sin[3]} -radix decimal} {{/TestCordic/sin[2]} -radix decimal} {{/TestCordic/sin[1]} -radix decimal} {{/TestCordic/sin[0]} -radix decimal}} -radixshowbase 0 -subitemconfig {{/TestCordic/sin[9]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[8]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[7]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[6]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[5]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[4]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[3]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[2]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[1]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/sin[0]} {-height 15 -radix decimal -radixshowbase 0}} /TestCordic/sin
add wave -noupdate -radix decimal -childformat {{{/TestCordic/arem[9]} -radix decimal} {{/TestCordic/arem[8]} -radix decimal} {{/TestCordic/arem[7]} -radix decimal} {{/TestCordic/arem[6]} -radix decimal} {{/TestCordic/arem[5]} -radix decimal} {{/TestCordic/arem[4]} -radix decimal} {{/TestCordic/arem[3]} -radix decimal} {{/TestCordic/arem[2]} -radix decimal} {{/TestCordic/arem[1]} -radix decimal} {{/TestCordic/arem[0]} -radix decimal}} -radixshowbase 0 -subitemconfig {{/TestCordic/arem[9]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[8]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[7]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[6]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[5]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[4]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[3]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[2]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[1]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/arem[0]} {-height 15 -radix decimal -radixshowbase 0}} /TestCordic/arem
add wave -noupdate -format Analog-Step -height 74 -max 825.0 -min -144.0 -radix decimal -childformat {{{/TestCordic/theCordic/x[10][10]} -radix decimal} {{/TestCordic/theCordic/x[10][9]} -radix decimal} {{/TestCordic/theCordic/x[10][8]} -radix decimal} {{/TestCordic/theCordic/x[10][7]} -radix decimal} {{/TestCordic/theCordic/x[10][6]} -radix decimal} {{/TestCordic/theCordic/x[10][5]} -radix decimal} {{/TestCordic/theCordic/x[10][4]} -radix decimal} {{/TestCordic/theCordic/x[10][3]} -radix decimal} {{/TestCordic/theCordic/x[10][2]} -radix decimal} {{/TestCordic/theCordic/x[10][1]} -radix decimal} {{/TestCordic/theCordic/x[10][0]} -radix decimal}} -radixshowbase 0 -subitemconfig {{/TestCordic/theCordic/x[10][10]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][9]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][8]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][7]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][6]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][5]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][4]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][3]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][2]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][1]} {-height 15 -radix decimal -radixshowbase 0} {/TestCordic/theCordic/x[10][0]} {-height 15 -radix decimal -radixshowbase 0}} {/TestCordic/theCordic/x[10]}
add wave -noupdate -format Analog-Step -height 74 -max 824.99999999999989 -min -824.0 -radix decimal -radixshowbase 0 {/TestCordic/theCordic/y[10]}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {8603000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 75
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 7500
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {5220900 ps} {20650400 ps}
